name: "➕ New channel group request"
description: "Suggest a batch of new public TV channels"
title: "[NEW GROUP] "
labels: ["new-channel"]
body:
  - type: input
    id: group_name
    attributes:
      label: Group Name / Description
      placeholder: "e.g. Regional channels - Basilicata"

  - type: textarea
    id: channels
    attributes:
      label: Channels List
      description: "Provide one channel per line in the format: Channel name | Stream URL | Notes (optional)"
      placeholder: |
        RAI 1 | https://example.com/rai1.m3u8 | main national channel
        RAI 2 | https://example.com/rai2.m3u8 | main national channel

  - type: input
    id: tested_players
    attributes:
      label: Tested Players
      description: "List the IPTV players where the channels have been verified"
      placeholder: "VLC, TiviMate, Kodi"

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes (optional)
      description: "Any extra information about the batch or streams"

    required: false
